//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeFleet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UriList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UriList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeFleet.Resources.UriList", typeof(UriList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tw.ogame.gameforge.com.
        /// </summary>
        public static string LandingUrl {
            get {
                return ResourceManager.GetString("LandingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lobby-api.ogame.gameforge.com/users/me/accounts.
        /// </summary>
        public static string OgameAccountList {
            get {
                return ResourceManager.GetString("OgameAccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lobby-api.ogame.gameforge.com.
        /// </summary>
        public static string OgameLobbyApiHost {
            get {
                return ResourceManager.GetString("OgameLobbyApiHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lobby.ogame.gameforge.com.
        /// </summary>
        public static string OgameLobbyHost {
            get {
                return ResourceManager.GetString("OgameLobbyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://lobby-api.ogame.gameforge.com/users/me/loginLink?id={0}&amp;server[language]={1}&amp;server[number]={2}.
        /// </summary>
        public static string OgameLoginUrl {
            get {
                return ResourceManager.GetString("OgameLoginUrl", resourceCulture);
            }
        }
    }
}
